// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALokcOr4KshUVUP2IdrL7WxzoJAhDmkPw',
    appId: '1:561291919905:web:942eae483f49e3c2bc1960',
    messagingSenderId: '561291919905',
    projectId: 'uptodo-8dd06',
    authDomain: 'uptodo-8dd06.firebaseapp.com',
    storageBucket: 'uptodo-8dd06.appspot.com',
    measurementId: 'G-K9EHSP2Y6S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApwzCNmKCugWQ-KPPy_XJX1Apf9SwXpZI',
    appId: '1:561291919905:android:d5985c5eb48fead3bc1960',
    messagingSenderId: '561291919905',
    projectId: 'uptodo-8dd06',
    storageBucket: 'uptodo-8dd06.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxAiPIYZUEvc6cFLBeQC4lD7HyNqFHo4I',
    appId: '1:561291919905:ios:b1e555a54b1bac2cbc1960',
    messagingSenderId: '561291919905',
    projectId: 'uptodo-8dd06',
    storageBucket: 'uptodo-8dd06.appspot.com',
    iosBundleId: 'com.example.uptodoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxAiPIYZUEvc6cFLBeQC4lD7HyNqFHo4I',
    appId: '1:561291919905:ios:b6630ba191cd7573bc1960',
    messagingSenderId: '561291919905',
    projectId: 'uptodo-8dd06',
    storageBucket: 'uptodo-8dd06.appspot.com',
    iosBundleId: 'com.example.uptodoApp.RunnerTests',
  );
}
