name: uptodo_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  font_awesome_flutter: ^10.6.0
  google_fonts: ^6.1.0
  google_sign_in: ^6.2.1
  intl: ^0.18.0
  local_auth: ^2.1.8
  logger: ^2.0.2+1
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  table_calendar: ^3.0.9

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/png/
    - assets/svg/
